name: gli
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable:
  dartz:
  get_it:
  internet_connection_checker:
  shared_preferences:
  hive:
  hive_flutter:
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^5.0.8
  bootstrap_icons: ^1.11.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner:
  hive_generator:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf


    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
