// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBACNofQVZP3lLtjxpjAxaHsSk9q57ZfK4',
    appId: '1:383334076494:web:ffda34ae605867a7d3331f',
    messagingSenderId: '383334076494',
    projectId: 'gli-task',
    authDomain: 'gli-task.firebaseapp.com',
    storageBucket: 'gli-task.appspot.com',
    measurementId: 'G-6PKKQ8KNDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC78hXKnDCCNomSNJ1Jsr4x7j4RNC0PruM',
    appId: '1:383334076494:android:3d725cf419f7c39bd3331f',
    messagingSenderId: '383334076494',
    projectId: 'gli-task',
    storageBucket: 'gli-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdTHKG3_IzXeL5XX3mZzHC6RYHVAWM3Qk',
    appId: '1:383334076494:ios:e7e6da5140c88047d3331f',
    messagingSenderId: '383334076494',
    projectId: 'gli-task',
    storageBucket: 'gli-task.appspot.com',
    iosBundleId: 'com.example.gli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdTHKG3_IzXeL5XX3mZzHC6RYHVAWM3Qk',
    appId: '1:383334076494:ios:e7e6da5140c88047d3331f',
    messagingSenderId: '383334076494',
    projectId: 'gli-task',
    storageBucket: 'gli-task.appspot.com',
    iosBundleId: 'com.example.gli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBACNofQVZP3lLtjxpjAxaHsSk9q57ZfK4',
    appId: '1:383334076494:web:49b012c99e57899ed3331f',
    messagingSenderId: '383334076494',
    projectId: 'gli-task',
    authDomain: 'gli-task.firebaseapp.com',
    storageBucket: 'gli-task.appspot.com',
    measurementId: 'G-QCGQVNES4S',
  );
}
