// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9c3VVFT0x97_jm6bOmnunjuwS1KqMX0',
    appId: '1:423324466011:web:4836e6a26f9bbabd61787e',
    messagingSenderId: '423324466011',
    projectId: 'f-society-de242',
    authDomain: 'f-society-de242.firebaseapp.com',
    storageBucket: 'f-society-de242.appspot.com',
    measurementId: 'G-TY0WE6C883',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJPhDMDQY_Wbdb4a77pYPuwc46Ni5CvE',
    appId: '1:423324466011:android:6b1bb8204c04e88f61787e',
    messagingSenderId: '423324466011',
    projectId: 'f-society-de242',
    storageBucket: 'f-society-de242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNxo8QwtCjn7fJdHocayGhspE_XhDypL8',
    appId: '1:423324466011:ios:79d34f113a05068061787e',
    messagingSenderId: '423324466011',
    projectId: 'f-society-de242',
    storageBucket: 'f-society-de242.appspot.com',
    iosBundleId: 'com.example.fsociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNxo8QwtCjn7fJdHocayGhspE_XhDypL8',
    appId: '1:423324466011:ios:36663dd45461c3c661787e',
    messagingSenderId: '423324466011',
    projectId: 'f-society-de242',
    storageBucket: 'f-society-de242.appspot.com',
    iosBundleId: 'com.example.fsociety.RunnerTests',
  );
}
